apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/oriree70/greyscale.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

