name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to K8s
      run: |

        curl -OL https://raw.githubusercontent.com/oriree70/greyscale/main/greyscale.yaml
        kubectl apply -f greyscale.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
