name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to K8s
      run: |
        kubectl apply -f argoGrey/greyscale.yaml --validate=false
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
