name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Authenticate to cluster
        env:
          K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
        run: |
          kubectl config set-cluster my-cluster --server=https://18.234.151.173:6443 --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions --token=$K8S_TOKEN
          kubectl config set-context my-cluster --cluster=my-cluster --user=github-actions
          kubectl config use-context my-cluster

      - name: Debug Kubernetes Connection
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f argoGrey/greyscale.yaml --validate=false






