name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: docker://bitnami/kubectl:latest

      - name: Authenticate to cluster
        env:
          K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
        run: |
          kubectl config set-cluster my-cluster --server=https://3.85.147.195:6443 --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions --token=$K8S_TOKEN
          kubectl config set-context my-cluster --cluster=my-cluster --user=github-actions
          kubectl config use-context my-cluster

      - name: Debug Kubernetes Connection
        run: |
          kubectl get nodes
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f argoGrey/greyscale.yaml --validate=false

      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/greyscale
      - name: Get Pods
        run: |
          kubectl get pods -o wide
      - name: Get SVC
        run: |
          kubectl get svc -o wide
          






